server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/userService/**
          - id: ticket-service
            uri: lb://ticket-service
            predicates:
              - Path=/api/v1/ticketService/**
          - id: vehicle-service
            uri: lb://vehicle-service
            predicates:
              - Path=/api/v1/vehicleService/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/paymentService/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka